export type MediaLinkCategory = "tv" | "press" | "music" | "concert";

export type MediaLink = {
  id: string;
  href: string;
  title: string;
  titleEn: string;
  source: string;
  category: MediaLinkCategory;
  thumbnailUrl: string;
  youtubeId?: string;
};

export const mediaLinks: MediaLink[] = [
  { id: "kulis-meyxana", href: "https://kulis.az/xeber/media/cavidan-fatihi-meyxanani-ciddi-senet-kimi-sirimayin-musahibe-52252", title: "Cavidan Fatihi: “Meyxananı ciddi sənət kimi sırımayın” – Müsahibə", titleEn: "Cavidan Fatihi: “Don’t portray meykhana as serious art” – Interview", source: "Kulis.az", category: "press", thumbnailUrl: "https://kulis.az/storage/news/2024/january/23/big/65b27535534b865b27535534b9170619422965b27535534b665b27535534b7.jpg" },
  { id: "bbc-azeri", href: "https://www.bbc.com/azeri/azerbaijan-45833081.amp", title: "Cavidan Fatihi: Atam demişdi, neynirsən gitaranı? İndi görürəm, evdəkilər fəxr edir", titleEn: "Cavidan Fatihi: My father used to say, ‘What are you doing with a guitar?’ Now I see my family is proud", source: "BBC News Azərbaycanca", category: "press", thumbnailUrl: "https://ichef.bbci.co.uk/news/1200/branded_azeri/CAC9/production/_103831915_screenshot2018-10-12at12.15.44.png" },
  { id: "youtube-1", href: "https://youtu.be/NN59gi9LCI8?si=FlTzd7g9NxRElFw4", title: "Cavidan Fatihi: Atam demişdi, neynirsən gitaranı?", titleEn: "Cavidan Fatihi: My father used to say, ‘What are you doing with the guitar?’", source: "BBC News Azərbaycanca", category: "tv", thumbnailUrl: "https://i.ytimg.com/vi/NN59gi9LCI8/hqdefault.jpg", youtubeId: "NN59gi9LCI8" },
  { id: "youtube-2", href: "https://youtu.be/DJhKjWCK8z4?si=aeEOerDvim_sw-v3", title: "Dəşti | Cavidan Fatihi | TEDxBHOS", titleEn: "Dəşti | Cavidan Fatihi | TEDxBHOS", source: "TEDx Talks", category: "tv", thumbnailUrl: "https://i.ytimg.com/vi/DJhKjWCK8z4/hqdefault.jpg", youtubeId: "DJhKjWCK8z4" },
  { id: "youtube-3", href: "https://youtu.be/Xjp9nuOXT-o?si=2ekCCTjiya6I3RfG", title: "Günə Bax | Cavidan Fatihi əsl ixtisasından danışdı | Yönümü dəyişmişəm", titleEn: "Günə Bax | Cavidan Fatihi talks about his original profession | I have changed direction", source: "ARB TV", category: "music", thumbnailUrl: "https://i.ytimg.com/vi/Xjp9nuOXT-o/hqdefault.jpg", youtubeId: "Xjp9nuOXT-o" },
  { id: "youtube-4", href: "https://youtu.be/e7YQ8wLw8D4?si=vlxM_yldp-n5kGPh", title: "Cavidan Fatihi — Sən Bir Başqasan (LIVE)", titleEn: "Cavidan Fatihi — You Are Different (LIVE)", source: "CırtdanPro", category: "music", thumbnailUrl: "https://i.ytimg.com/vi/e7YQ8wLw8D4/hqdefault.jpg", youtubeId: "e7YQ8wLw8D4" },
  { id: "youtube-5", href: "https://youtu.be/xP4HMtzKR5A?si=lT0REBw7RMxkUkXE", title: "Cavidan Fatihi — Sənsiz (LIVE)", titleEn: "Cavidan Fatihi — Without You (LIVE)", source: "CırtdanPro", category: "tv", thumbnailUrl: "https://i.ytimg.com/vi/xP4HMtzKR5A/hqdefault.jpg", youtubeId: "xP4HMtzKR5A" },
  { id: "youtube-6", href: "https://youtu.be/fseRT9jPDfQ?si=fqLceabSMF4vf86K", title: "İntizar | Cavidan Fatihi | TEDxBHOS", titleEn: "Longing | Cavidan Fatihi | TEDxBHOS", source: "TEDx Talks", category: "tv", thumbnailUrl: "https://i.ytimg.com/vi/fseRT9jPDfQ/hqdefault.jpg", youtubeId: "fseRT9jPDfQ" },
  { id: "edebiyyat-incesenet", href: "https://www.edebiyyatveincesenet.az/musiqi/item/13846-dzhokh-faerzhli-taerzlaer-eshidaedzaeksiniz-dzavidan-fatehlae-musahibae", title: "“Çox fərqli tərzlər eşidəcəksiniz…” - CAVİDAN FATİHİLƏ MÜSAHİBƏ", titleEn: "“You will hear very different styles…” – Interview with Cavidan Fatihi", source: "Ədəbiyyat və İncəsənət", category: "press", thumbnailUrl: "https://www.edebiyyatveincesenet.az/media/k2/items/cache/69117e8d209efe150e4637070c826491_XL.jpg" },
  { id: "youtube-7", href: "https://youtu.be/GwMphNG6PAo?si=xlybpBYgLFLbQBx7", title: "Trendə düşən müğənnidən maraqlı açıqlamalar - Ekstra müsahibə", titleEn: "Interesting statements from the singer trending now – Extra interview", source: "APA TV", category: "music", thumbnailUrl: "https://i.ytimg.com/vi/GwMphNG6PAo/hqdefault.jpg", youtubeId: "GwMphNG6PAo" },
  { id: "azerbaijan-news-festival", href: "https://azerbaijan-news.az/az/posts/detail/heyder-eliyev-merkezinin-parkinda-yay-festivalinin-baglanis-konserti-teskil-olunub-1724650229", title: "Heydər Əliyev Mərkəzinin parkında “Yay Festivalı”nın bağlanış konserti təşkil olunub", titleEn: "A closing concert of the “Summer Festival” was held in the park of the Heydar Aliyev Center", source: "Azərbaycan Xəbərləri", category: "concert", thumbnailUrl: "https://eu2.contabostorage.com/71933ea89b5a4d0ca528a15679956e5d:azerbaijannews/uploads/img/posts/2024/08/26/172464776761905260_1200x630jpg-1724650216.jpg" },
  { id: "youtube-8", href: "https://youtu.be/dxPcy2T9i3o?si=ngI3jjFv_epvzWk-", title: "YERALTI: söhbət var #58 ŞAHİN ƏLİZADƏ, CAVİDAN FATİHİ, ZAUR KƏRİMLİ | “Əsgər mahnıları” YERALTI", titleEn: "YERALTI: conversation #58 ŞAHİN ƏLİZADƏ, CAVİDAN FATİHİ, ZAUR KƏRİMLİ | “Soldier songs” YERALTI", source: "YERALTI", category: "concert", thumbnailUrl: "https://i.ytimg.com/vi/dxPcy2T9i3o/hqdefault.jpg", youtubeId: "dxPcy2T9i3o" },
  { id: "azertag-festival", href: "https://azertag.az/xeber/heyder_eliyev_merkezinin_parkinda_yay_festivalinin_baglanis_konserti_teskil_olunub_video-3149914", title: "Heydər Əliyev Mərkəzinin parkında “Yay Festivalı”nın bağlanış konserti təşkil olunub (VİDEO)", titleEn: "A closing concert of the “Summer Festival” was held in the park of the Heydar Aliyev Center (VIDEO)", source: "AZƏRTAC", category: "concert", thumbnailUrl: "https://eu2.contabostorage.com/71933ea89b5a4d0ca528a15679956e5d:azerbaijannews/uploads/img/posts/2024/08/26/172464776761905260_1200x630jpg-1724650216.jpg" },
  { id: "525-social-media", href: "https://525.az/news/166139-sosial-media-menim-ucun-daha-elcatandir-cavidan-fatihi", title: "“Sosial media mənim üçün daha əlçatandır” - Cavidan Fatihi", titleEn: "“Social media is more accessible for me” – Cavidan Fatihi", source: "525-ci qəzet", category: "press", thumbnailUrl: "https://525.az/img/pics/large/2021-04/189250_kzj3zvgc0u.jpg" },
  { id: "lent-cana-cana", href: "https://lent.az/xeber/maqazin/cavidan-fatihi-menden-can-cana-oxumagimi-isteyirler-40657258", title: "Cavidan Fatihi: “Məndən “Can-cana\" oxumağımı istəyirlər”", titleEn: "Cavidan Fatihi: “They want me to sing ‘Can-cana’”", source: "Lent.az", category: "press", thumbnailUrl: "https://lent.az/storage/news/2026/january/14/big/6967a48f0b7226967a48f0b72317684000156967a48f0b71f6967a48f0b721.webp" },
  { id: "youtube-9", href: "https://youtu.be/YFsHp_mYPI8?si=MkHzWsxrlZtIous9", title: "Cavidan Fatihi & Çimnaz Sultanova - Fortuna 12.05.2022", titleEn: "Cavidan Fatihi & Çimnaz Sultanova - Fortuna 12.05.2022", source: "ATV Show", category: "tv", thumbnailUrl: "https://i.ytimg.com/vi/YFsHp_mYPI8/hqdefault.jpg", youtubeId: "YFsHp_mYPI8" },
  { id: "qht-5-ilin-zefer", href: "https://qht.az/az/xeber/5-ilin-zefer-sedasi-adli-konsert-proqrami-kecirilib-fotolar", title: "“5 ilin Zəfər sədası” adlı konsert proqramı keçirilib - FOTOLAR", titleEn: "The concert programme “Echo of five years of victory” was held – PHOTOS", source: "QHT.az", category: "concert", thumbnailUrl: "https://qht.az/media-sources/9d3364a0295840c9a80be7731d7e175806112025220332969.jpg" },
  { id: "teleqraf-157499", href: "https://teleqraf.az/news/senet/157499.html", title: "Cavidan: \"Utanmalı iş deyil, hər şey kafedən başladı...\" - Video", titleEn: "Cavidan: “It is not shameful, everything started in a cafe…” – Video", source: "Teleqraf.az", category: "press", thumbnailUrl: "https://teleqraf.az/storage/2017/12/04/7135.jpg" },
];
