import { Button } from "@/components/ui/button";
import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { useCart } from "@/contexts/CartContext";
import { useLocale } from "@/contexts/LocaleContext";
import { formatMoney } from "@/lib/format";
import { Minus, Plus, ShoppingBag, Trash2 } from "lucide-react";

export function CartDrawer() {
  const { locale } = useLocale();
  const { cart, isOpen, closeCart, loading, updateQuantity, removeItem, proceedToCheckout } = useCart();
  const copy = locale === "az" ? { title: "Səbət", empty: "Səbətiniz hazırda boşdur.", hint: "Seçilmiş məhsullar burada görünəcək.", total: "Cəmi", checkout: "Ödənişə keç", remove: "Məhsulu səbətdən sil", decrease: "Miqdarı azalt", increase: "Miqdarı artır" } : { title: "Bag", empty: "Your bag is currently empty.", hint: "Selected items will appear here.", total: "Total", checkout: "Continue to checkout", remove: "Remove item from bag", decrease: "Decrease quantity", increase: "Increase quantity" };
  return <Sheet open={isOpen} onOpenChange={open => !open && closeCart()}><SheetContent className="border-white/15 bg-black text-white"><SheetHeader className="border-b border-white/15 px-6 py-5"><SheetTitle className="flex items-center gap-2 text-white"><ShoppingBag className="size-4" />{copy.title}</SheetTitle></SheetHeader><div className="flex h-full flex-col px-6 pb-6 pt-2">{!cart?.items.length ? <div className="flex flex-1 flex-col items-center justify-center text-center"><ShoppingBag className="mb-4 size-9 text-zinc-600" /><p className="font-medium">{copy.empty}</p><p className="mt-2 text-sm text-zinc-500">{copy.hint}</p></div> : <><div className="flex-1 space-y-5 overflow-y-auto py-5">{cart.items.map(item => <div key={item.lineId} className="flex gap-3">{item.image ? <img src={item.image.url} alt={item.image.altText ?? item.productTitle} className="size-16 object-cover" /> : <div className="size-16 bg-zinc-900" />}<div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><p className="text-sm font-semibold">{item.productTitle}</p><button aria-label={`${copy.remove}: ${item.productTitle}`} onClick={() => removeItem(item.lineId)} className="text-zinc-500 hover:text-white"><Trash2 className="size-4" /></button></div><p className="mt-1 text-sm text-zinc-400">{formatMoney(item.lineTotal)}</p><div className="mt-3 flex items-center gap-3"><button aria-label={copy.decrease} disabled={loading} onClick={() => updateQuantity(item.lineId, Math.max(0, item.quantity - 1))} className="border border-white/20 p-1"><Minus className="size-3" /></button><span className="w-4 text-center text-xs">{item.quantity}</span><button aria-label={copy.increase} disabled={loading} onClick={() => updateQuantity(item.lineId, item.quantity + 1)} className="border border-white/20 p-1"><Plus className="size-3" /></button></div></div></div>)}</div><div className="border-t border-white/15 pt-5"><div className="mb-4 flex justify-between text-sm"><span className="text-zinc-400">{copy.total}</span><strong>{formatMoney(cart.total)}</strong></div><Button className="w-full rounded-none bg-white text-black hover:bg-zinc-200" onClick={proceedToCheckout}>{copy.checkout}</Button></div></>}</div></SheetContent></Sheet>;
}
